[build]
beforeBuildCommand = "" # covered at Awesome.toml
beforeDevCommand = "" # covered at Awesome.toml
devPath = "http://localhost:4567/" # port matches next dev -p 4567 at package.json
distDir = "../out" # nextjs export folder

[package]
productName = "tauri-todo"
version = "0.1.0"

[tauri.allowlist]
all = false

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = [ ]
icon = [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
identifier = "my.tauri-todo"
longDescription = ""
resources = [ ]
shortDescription = ""
targets = "all"

[tauri.bundle.deb]
depends = [ ]

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = [ ]

[tauri.bundle.windows]
digestAlgorithm = "sha256"
timestampUrl = ""

[tauri.security]

[tauri.updater]
active = false

[[tauri.windows]]
title = "tauri-todo"
fullscreen = false
resizable = true
